version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - 30000:30000
  #   depends_on:
  #     - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf